//! Writes `.apks` archives: a ZIP of split APKs plus a JSON table of contents.
//!
//! Files are stored (not recompressed) and copied byte-for-byte, so every APK inside keeps its
//! original signature. The archive is accepted by split-APK installers that take a ZIP of APKs
//! (e.g. SAI) and can be installed with `unzip` + `adb install-multiple splits/*.apk`.
//! It is NOT bundletool's `.apks` format (which requires a `toc.pb` generated by bundletool).

use serde::Serialize;
use std::fs::File;
use std::io::{self, Write};
use std::path::Path;
use zip::write::SimpleFileOptions;

#[derive(Debug, Clone, Serialize)]
pub struct ApksEntry {
    pub file: String,
    pub split: Option<String>,
    pub sha256: String,
    pub size: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct ApksToc {
    pub format: &'static str,
    pub package: String,
    pub version_code: i64,
    pub entries: Vec<ApksEntry>,
    pub install_hint: &'static str,
}

/// `members`: (archive file name, source path, split name, sha256 hex, size).
pub fn write_apks(out: &Path, package: &str, version_code: i64, members: &[(String, &Path, Option<String>, String, u64)]) -> io::Result<()> {
    let tmp = out.with_extension("apks.tmp");
    {
        let f = File::create(&tmp)?;
        let mut z = zip::ZipWriter::new(f);
        let opts = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored).large_file(false);
        let mut entries = Vec::new();
        for (name, path, split, sha, size) in members {
            let safe = name.replace(['/', '\\'], "_");
            let arc = format!("splits/{safe}");
            z.start_file(&arc, opts).map_err(io::Error::other)?;
            let mut src = File::open(path)?;
            io::copy(&mut src, &mut z)?;
            entries.push(ApksEntry { file: arc, split: split.clone(), sha256: sha.clone(), size: *size });
        }
        let toc = ApksToc {
            format: "uad-apks/1",
            package: package.into(),
            version_code,
            entries,
            install_hint: "unzip the archive and run: adb install-multiple splits/*.apk",
        };
        z.start_file("uad-apks.json", SimpleFileOptions::default()).map_err(io::Error::other)?;
        z.write_all(&serde_json::to_vec_pretty(&toc).map_err(io::Error::other)?)?;
        z.finish().map_err(io::Error::other)?;
    }
    std::fs::rename(tmp, out)
}
